### PR TITLE
Create git.md

### PR DESCRIPTION
**Pull request by emma-r-slight**
Start of a readme to help people with GIT..

### CODE REVIEW

**Comment by Aprillion** [comment]
Hm, thank for starting to improve our git documentation!

I would probably prefer a section in README for `Git`, probably right after `Workflow`, not a separate file...

Another piece of discussion is that core members have write access and previously we were just cloning the raid-fork without creating another person-fork. Thus current situation is like:

* Core members: `gh repo clone https://github.com/OpenSourceRaidGuild/website.git`
* Other contributors: `gh repo fork --clone --remote https://github.com/OpenSourceRaidGuild/website.git`

I am all for per-person forking of the raid-fork repo,, but at least one person needs to keep track of the upstream changes (to update the raid-fork if there are any changes unrelated to raid merged into original repo). Should be possible to set more 3 git remotes without problems though (origin = per-person fork, upstream = raid-fork, upstream2 = original repo).

**Comment by Aprillion** [comment]
Another piece of discussion is that core members have write access and previously we were just cloning the raid-fork without creating another person-fork. Thus current situation is like:

* Core members: `gh repo clone https://github.com/OpenSourceRaidGuild/website.git`
* Other contributors: `gh repo fork --clone --remote https://github.com/OpenSourceRaidGuild/website.git`

I am all for per-person forking of the raid-fork repo,, but at least one person needs to keep track of the upstream changes (to update the raid-fork if there are any changes unrelated to raid merged into original repo). Should be possible to set more 3 git remotes without problems though (origin = per-person fork, upstream = raid-fork, upstream2 = original repo).

**Comment by emma-r-slight** [comment]
> Thanks for starting to improve our git documentation!
> 
> I would probably prefer a section in README for `Git`, probably right after `Workflow`, not a separate file...

I think it depends on who the target audience is for the information... I was going for the Newbie raider...never contributed to open source, relatively new to git. So I planned on writing a fairly detailed How to git...instructions.

I think we could have a basic outline in the readme section you mentioned as well?

**Comment by emma-r-slight** [comment]
> I am all for per-person forking of the raid-fork repo,, but at least one person needs to keep track of the upstream changes (to update the raid-fork if there are any changes unrelated to raid merged into original repo). Should be possible to set 3 git remotes without problems though (origin = per-person fork, upstream = raid-fork, upstream2 = original repo).

My target for this how-to git is like I mentioned - newbie raider so forking the raid repo to make PR from and setting upstream remote for updates to master branch should be fine??

**Comment by Aprillion** [comment]
> My target for this how-to git is like I mentioned - newbie raider so forking the raid repo to make PR from and setting upstream remote for updates to master branch should be fine??

Yup, in the instructions for newbies that should be enough, fork raid repo, clone your fork and set up 1 additional git remote, upstream to the raid repo.

(hmm, not sure why github doesn't have threads for these commends)

**Comment by JacobMGEvans** [comment]
> > My target for this how-to git is like I mentioned - newbie raider so forking the raid repo to make PR from and setting upstream remote for updates to master branch should be fine??
> 
> Yup, in the instructions for newbies that should be enough, fork raid repo, clone your fork and set up 1 additional git remote, upstream to the raid repo.
> 
> (hmm, not sure why github doesn't have threads for these comments)

Apparently, it wasn't lol

**Pull request merged**
